vim.g.symbols_outline = {
  highlight_hovered_item = true,
  show_guides = true,
  auto_preview = true,
  position = 'right',
  relative_width = true,
  width = 50,
  auto_close = false,
  show_numbers = false,
  show_relative_numbers = false,
  show_symbol_details = false,
  preview_bg_highlight = 'Pmenu',
  keymaps = { -- These keymaps can be a string or a table for multiple keys
    close = {"<Esc>", "q"},
    goto_location = "<Cr>",
    focus_location = "o",
    hover_symbol = "<C-space>",
    toggle_preview = "K",
    rename_symbol = "r",
    code_actions = "a",
  },
  lsp_blacklist = {},
  symbol_blacklist = {},
  symbols = {
    File = {icon = "", hl = "CmpItemKindFile"},
    Module = {icon = "", hl = "CmpItemKindModule"},
    Namespace = {icon = "", hl = "CmpItemKindNamespace"},
    Package = {icon = "", hl = "CmpItemKindNamespace"},
    Class = {icon = "𝓒", hl = "CmpItemKindType"},
    Method = {icon = "ƒ", hl = "CmpItemKindMethod"},
    Property = {icon = "", hl = "CmpItemKindMethod"},
    Field = {icon = "", hl = "CmpItemKindField"},
    Constructor = {icon = "", hl = "CmpItemKindConstructor"},
    Enum = {icon = "ℰ", hl = "CmpItemKindType"},
    Interface = {icon = "ﰮ", hl = "CmpItemKindType"},
    Function = {icon = "", hl = "CmpItemKindFunction"},
    Variable = {icon = "", hl = "CmpItemKindConstant"},
    Constant = {icon = "", hl = "CmpItemKindConstant"},
    String = {icon = "𝓐", hl = "CmpItemKindString"},
    Number = {icon = "#", hl = "CmpItemKindNumber"},
    Boolean = {icon = "⊨", hl = "CmpItemKindBoolean"},
    Array = {icon = "", hl = "CmpItemKindConstant"},
    Object = {icon = "⦿", hl = "CmpItemKindType"},
    Key = {icon = "🔐", hl = "CmpItemKindType"},
    Null = {icon = "NULL", hl = "CmpItemKindType"},
    EnumMember = {icon = "", hl = "CmpItemKindField"},
    Struct = {icon = "𝓢", hl = "CmpItemKindType"},
    Event = {icon = "", hl = "CmpItemKindType"},
    Operator = {icon = "+", hl = "CmpItemKindOperator"},
    TypeParameter = {icon = "𝙏", hl = "CmpItemKindParameter"}
  }
}
