return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "tokyonight-storm",
      icons = {
        kinds = {
          Array = " ",
          Boolean = " ",
          Class = "ﴯ ",
          Copilot = " ",
          Key = " ",
          Namespace = " ",
          Null = "ﳠ ",
          Number = " ",
          Object = " ",
          Package = " ",
          String = " ",
          Text = " ",
          Method = " ",
          Function = " ",
          Constructor = " ",
          Field = "ﰠ ",
          Variable = " ",
          Interface = " ",
          Module = " ",
          Property = "ﰠ ",
          Unit = "塞 ",
          Value = " ",
          Enum = " ",
          Keyword = " ",
          Snippet = " ",
          Color = " ",
          File = " ",
          Reference = " ",
          Folder = " ",
          EnumMember = " ",
          Constant = " ",
          Struct = "פּ ",
          Event = " ",
          Operator = " ",
          TypeParameter = " ",
          Robot = "ﮧ ",
          Smiley = "ﲃ ",
          Note = " ",
        },
      },
    },
  },
}
