#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# yabai -m rule --add app="^企业微信" manage=off

# global settings
yabai -m config external_bar                 all:32:0
yabai -m config menubar_opacity              1.0
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config display_arrangement_order    default
yabai -m config window_origin_display        default
# 当前屏幕下，新窗口出现在屏幕的哪个位置
yabai -m config window_placement             second_child
yabai -m config window_zoom_persist          on
yabai -m config window_shadow                on
yabai -m config window_animation_duration    0.0
yabai -m config window_animation_easing      ease_out_circ
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_opacity               on
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   08
# 布局模式
# - bsp: 平铺
# - stack: 堆叠
# - flaot: 浮动
yabai -m config layout                       bsp
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_modifier ctrl
# 在平铺管理的情况下，拖动一个窗口到另外一个窗口位置时的操作：
# - swap: 交换窗口位置
# - stack: 将窗口叠加在另外一个窗口上
yabai -m config mouse_drop_action swap

yabai -m rule --add app="^VLC$" manage=off

echo "yabai configuration loaded.."
