require('user.options')
require('user.keymaps')
require('user.plugins')
require('user.colors')
require('user.galaxyline')

require('user.autocmd')
require('user.coc')
require('user.comment')
require('user.cmp')
require('user.floaterm')
require('user.git')
require('user.gitsigns')
require('user.golang')
require('user.indent-blankline')
require('user.lsp')
require('user.lspsaga')
require('user.rainbow')
require('user.renamer')
require('user.nvim-tree')
require('user.neoscroll')
require('user.telescope')
require('user.treesitter')

require('user.whichkey')
