require('user.options')
require('user.keymaps')
require('user.plugins')
require('user.colors')

-- require('user.hotreload')
require('user.git')
require('user.coc')
require('user.rainbow')
require('user.floaterm')
require('user.neoscroll')
require('user.telescope')
require('user.lsp')
require('user.lspsaga')
require('user.renamer')
require('user.nvim-tree')
require('user.whichkey')
