require('user.options')

require('user.keymaps')
require('user.plugins')
require('user.colors')
require('user.galaxyline')

require('user.alpha')
require('user.autocmd')
require('user.bufferline')
require('user.comment')
require('user.cmp')
require('user.dressing')
require('user.floaterm')
require('user.git')
require('user.gitsigns')
require('user.golang')
require('user.indent-blankline')
require('user.lsp')
require('user.lspsaga')
require('user.nvim-tree')
require('user.neoscroll')
require('user.project')
require('user.rainbow')
require('user.renamer')
require('user.surround')
require('user.symbol-outline')
require('user.telescope')
require('user.treesitter')
require('user.zen')

require('user.whichkey')

